### ISSUE TITLE
res['limits']['cpu'] error in k8s backend when setting cpu requests

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#262]

**Comment by o-smirnov** [comment]
@JSKenyon try this branch please.

**Comment by JSKenyon** [comment]
I think that there is still a larger bug here:

https://github.com/caracal-pipeline/stimela/blob/9b6301813465b88dc1e44e5e6cac90af0163532b/stimela/backends/kube/__init__.py#L261-L281

This function can currently exit with `_kube_namepsace` set to `None`. I believe the problem is line 274 - surely it should be above the `break`?

**Comment by JSKenyon** [comment]
With the above change, my example works i.e. moving the setting of `_kube_namespace` to above the `break`. I suspect that isn't a perfect solution though. Did the example run for you without changing this @o-smirnov?

**Comment by o-smirnov** [comment]
Ooops, I was being blind. Or drunk. No, it is the perfectly correct solution I believe. It finds the current context and retrieves the namespace from it, else uses "default".

Please update and test again.

Yes it ran for me, but I know why. Due to a quirk of my .kube/config, I had another context defined before the current context that was using the same namespace. So the bug actually served to assign the correct value in my case.

**Comment by JSKenyon** [comment]
Ok - example now runs as expected on this branch.
